### ISSUE TITLE
Пакет noodlehaus/config больше не поддерживается

### ISSUE THREAD

**Issue by andreyryabin** [cjp2600/bim-core#10]
Добрый день, пакет noodlehaus/config, используемый в этом решении больше не поддерживается.
Планируется ли его замена?

Package noodlehaus/config is abandoned, you should avoid using it. No replacement was suggested.

**Comment by cjp2600** [comment]
Добрый день, спасибо что указали на не поддерживаемый пакет, да конечно заменим его в следующей версии думаю на  (symfony/config). К сожалению не всегда есть возможность следить за актуальностью и активно вести разработку пакета, так что мы приветствуем участие в проекте, do pull requests ))

**Comment by andreyryabin** [comment]
Ловите, написал маленький класс https://github.com/cjp2600/bim-core/pull/11
